<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="clownbot">
  <xacro:include filename="$(find clownbot_description)/urdf/common.xacro"/>
  <xacro:include filename="$(find clownbot_description)/urdf/base/base.xacro"/>
  <xacro:include filename="$(find clownbot_description)/urdf/wheels/wheel.xacro"/>
  <xacro:include filename="$(find clownbot_description)/urdf/wheels/caster.xacro"/>

  <xacro:property name="base_to_wheel_offset_y" value="0.15"/>
  <xacro:property name="base_to_caster_offset_x" value="0.1"/>
  <xacro:property name="base_to_caster_offset_z" value="${wheel_radius - caster_radius}"/>

  <link name="base_footprint"/>

  <xacro:base name="base_link" parent="base_footprint">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </xacro:base>

  <xacro:right_wheel name="right_wheel" parent="base_link">
    <origin xyz="0 ${-1 * base_to_wheel_offset_y} 0" rpy="0 0 0"/>
  </xacro:right_wheel>

  <xacro:left_wheel name="left_wheel" parent="base_link">
    <origin xyz="0 ${base_to_wheel_offset_y} 0" rpy="0 0 0"/>
  </xacro:left_wheel>

  <xacro:caster name="front_caster" parent="base_link">
    <origin xyz="${base_to_caster_offset_x} 0 ${-1 * base_to_caster_offset_z}" rpy="0 0 0"/>
  </xacro:caster>

  <xacro:caster name="back_caster" parent="base_link">
    <origin xyz="${-1 * base_to_caster_offset_x} 0 ${-1 * base_to_caster_offset_z}" rpy="0 0 0"/>
  </xacro:caster>
</robot>
