#!/usr/bin/env sh

if [ $# = 4 ]; then
  pkg=$1
  system=$2
  entry=$3
  output=$4
  cat > $output <<EOF
#!/usr/bin/env sh
#|-*- mode:lisp -*-|#
#|
exec /usr/bin/env sbcl --noinform --load \$(rospack find roslisp)/scripts/roslisp-sbcl-init --load \$HOME/quicklisp/setup.lisp --script "\$0" "\$@"
|#

(ros-load:load-system "${pkg}" "${system}")
(${entry})
EOF
  chmod a+x $output
else
  echo "Usage: make_lisp_script <pkg> <system> <entry> <output>"
  exit 1
fi
